refactor: update auth pages to new design
rotki/rotki.com pull request #122
Opened 2023-07-31 11:36 UTC by lukicenturi

Closes #113

2023-07-31 11:41 UTC, lukicenturi commented
To test using the new markdown, in `nuxt.config.ts` line 165 change to 
```
        repo: 'lukicenturi/rotki.com',
        branch: 'jobs',
```

2023-07-31 15:08 UTC, tewshi requested changes

2023-07-31 15:16 UTC, lukicenturi commented on pages/jobs/JobTag.vue
you mean the whole component? It use <RuiChip/ > inside.

2023-07-31 15:37 UTC, tewshi commented on pages/jobs/JobTag.vue
I meant to move this file to components

2023-07-31 16:30 UTC, lukicenturi commented on pages/jobs/JobTag.vue
oh sorry, see that now, updated

2023-07-31 17:18 UTC, tewshi approved these changes
lgtm!

2023-08-03 13:23 UTC, kelsos approved these changes

2023-08-03 13:23 UTC, merged