feat: values page
rotki/rotki.com pull request #144
Opened 2023-08-24 07:45 UTC by lukicenturi

Closes #140

2023-08-28 10:02 UTC, kelsos requested changes
So there are a few minor comments but overall it looks good.
I checked both mobile/desktop layouts and the look great.

2023-08-28 10:02 UTC, kelsos commented on components/values/ValueContact.vue
> +    icon: 'chat-smile-2-line',
Ok so instead of copy pasting the urls/mail addresses do you think we can move them instead to config?

2023-09-04 11:35 UTC, tewshi approved these changes
lgtm!

2023-09-12 07:23 UTC, kelsos approved these changes
lgtm, thanks :)

2023-09-12 07:23 UTC, merged